import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "../utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Type Fight!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <Link href="/auth" className="text-lg font-bold">
          Auth
        </Link>
        <Link href="/fights" className="text-lg font-bold">
          Fights
        </Link>
      </div>
    </>
  );
};

export default Home;
