import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import io from "socket.io-client";
import { api } from "../utils/api";
import {
  ChangeEvent,
  Dispatch,
  SetStateAction,
  useEffect,
  useState,
} from "react";

const socket = io("http://localhost:5000");

const Home: NextPage = () => {
  const [connected, setConnected]: [
    boolean,
    Dispatch<SetStateAction<boolean>>
  ] = useState(false);
  const [userInput, setUserInput] = useState<string>("");
  const [correct, setCorrect] = useState<boolean>(false);

  useEffect(() => {
    //Trigger on connect
    socket.on("connect", () => {
      setConnected(true);
    });

    //Trigger on disconnect
    socket.on("disconnect", () => {
      setConnected(false);
    });

    //Trigger when sent correct
    socket.on("correct", () => {
      setCorrect(true);
    });

    return () => {
      socket.off("connect");
      socket.off("disconnect");
      socket.off("correct");
      socket.off("userInput");
    };
  });

  useEffect(() => {
    //Send user input to server for validation
    socket.emit("userInput", userInput);
  }, [userInput]);

  return (
    <>
      <Head>
        <title>Type Fight!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col flex-wrap p-8">
        <p>{`Connected: ${connected ? "👍" : "👎"}`}</p>
        <h1>{correct ? "🎉" : null}</h1>
        <label htmlFor="text">Input</label>
        <input
          type="text"
          name="text"
          id="text"
          className="border border-slate-600"
          value={userInput}
          onChange={(e) => {
            if (!correct) {
              setUserInput(e.target.value);
              return;
            }
            return;
          }}
        />
      </div>
    </>
  );
};

export default Home;
