import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import io, { Socket } from "socket.io-client";
import { api } from "../utils/api";
import {
  ChangeEvent,
  Dispatch,
  SetStateAction,
  useEffect,
  useState,
} from "react";
import { urls } from "../utils/url";

const Home: NextPage = () => {
  const [socket, setSocket] = useState<Socket | null>(null);
  const [userInput, setUserInput] = useState<string>("");
  const [correct, setCorrect] = useState<boolean>(false);

  useEffect(() => {
    const connect = io(urls.api) ?? null;
    //Trigger on connect
    connect.on("connect", () => {
      setSocket(connect);
    });

    //Trigger on disconnect
    connect.on("disconnect", () => {
      setSocket(null);
    });

    //Trigger when sent correct
    connect.on("correct", () => {
      setCorrect(true);
    });

    return () => {
      connect.disconnect();
    };
  }, []);

  useEffect(() => {
    //Send user input to server for validation
    if (socket) {
      socket.emit("userInput", userInput);
    }
  }, [socket, userInput]);

  return (
    <>
      <Head>
        <title>Type Fight!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col flex-wrap p-8">
        <p>{`Connected: ${socket ? "👍" : "👎"}`}</p>
        <h1>{correct ? "🎉" : null}</h1>
        <label htmlFor="text">Input</label>
        <h2>Hej hej</h2>
        <input
          type="text"
          name="text"
          id="text"
          className="border border-slate-600"
          value={userInput}
          onChange={(e) => {
            if (!correct) {
              setUserInput(e.target.value);
              return;
            }
            return;
          }}
        />
      </div>
    </>
  );
};

export default Home;
